### ISSUE TITLE
最新版按enter键还是报这个错

### ISSUE THREAD

**Issue by hqzh** [Leecason/element-tiptap#132] opened 2020-06-29 08:28 UTC
:tada: This issue has been resolved in version 1.24.4 :tada:

The release is available on:
- [GitHub release](https://github.com/Leecason/element-tiptap/releases/tag/%401.24.4)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/element-tiptap/v/1.24.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

_Originally posted by @Leecason in https://github.com/Leecason/element-tiptap/issues/129#issuecomment-650561122_

**Comment by hqzh** [comment] 2020-06-29 08:28
https://github.com/Leecason/element-tiptap/issues/129

**Comment by hqzh** [comment] 2020-06-29 08:30
[https://leecason.github.io/element-tiptap/](demo)可以看简单版的demo就有这个问题

**Comment by Leecason** [comment] 2020-06-29 08:36
> [demo](https://leecason.github.io/element-tiptap)可以看简单版的demo就有这个问题

忘了更新 demo site，现在应该可以了

**Comment by hqzh** [comment] 2020-06-30 02:11
@Leecason demo好了，npm包不会没更新吧，我本地用的"element-tiptap": "^1.24.5",还有这个问题

**Comment by Leecason** [comment] 2020-06-30 12:09
Duplicate of https://github.com/Leecason/element-tiptap/issues/129

**Closed** 2020-06-30 12:10 UTC

**Comment by hqzh** [comment] 2020-07-02 02:54
```js
  "resolutions": {
        "prosemirror-model": "1.9.1"
    },
```
在自己项目中的package.json加上以上代码解决了，感谢！
